name: pokeapp
description: A Flutter application for Pokemon information
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: 5.9.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.1
  flutter_svg: ^2.2.1
  go_router: ^16.2.4
  get_it: ^8.2.0
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.14.4
  flutter_lints: ^2.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  riverpod_generator: ^2.6.2
  json_serializable: ^6.8.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images_svg/
    - assets/icons/bottom_navigation_bar/
    - assets/icons/details/
    - assets/icons/favorite/
    - assets/icons/pokemon_type/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
